---
- name: Deploy Todo App to Kubernetes
  hosts: localhost
  connection: local

  tasks:

    - name: Create Namespace
      command: kubectl apply -f rbac/namespace.yaml

    - name: Create Service Account
      command: kubectl apply -f rbac/serviceaccount.yaml

    - name: Create Role
      command: kubectl apply -f rbac/role.yaml

    - name: Create RoleBinding
      command: kubectl apply -f rbac/rolebinding.yaml

    - name: Deploy Application
      command: kubectl apply -f Kubernetes/deployment.yaml

    - name: Create Service
      command: kubectl apply -f Kubernetes/service.yaml
